feat: report error location when interpreting files
Danielmelody/Ruschm pull request #38
Opened 2020-09-10 13:39 UTC by Danielmelody

2020-09-10 13:40 UTC, Danielmelody commented
Try add some invalid syntax and get the syntax error.

Semantic error location would soon been supported.

2020-09-11 04:02 UTC, CurryPseudo requested changes

2020-09-11 04:06 UTC, Danielmelody commented on src/error.rs
> +    pub fn set_location(mut self, location: Option<[u32; 2]>) -> Self {
This is a owned builder pattern

2020-09-11 04:11 UTC, CurryPseudo commented on src/error.rs
> +    pub fn set_location(mut self, location: Option<[u32; 2]>) -> Self {
Ok, I get it.
But, for builder pattern, I think with_location or located is more appropriate.

2020-09-11 04:17 UTC, Danielmelody commented
Updated.

2020-09-11 06:39 UTC, merged